import { Server } from './types';

export const mockServers: Server[] = [
  {
    id: '1',
    name: 'HK-Node-01',
    region: '香港',
    datacenter: 'HKBN',
    cpu: 'Intel Xeon E5-2680 v4',
    cpuCores: 28,
    memory: 128,
    disk: 2000,
    diskType: 'SSD',
    virtualization: 'KVM',
    publicIp: '203.0.113.1',
    internalIp: '10.0.0.100',
    bandwidth: 1000,
    maxVms: 50,
    currentVms: 32,
    status: 'online',
    enabled: true,
    cpuUsage: 45,
    memoryUsage: 62,
    diskUsage: 58,
  },
  {
    id: '2',
    name: 'JP-Node-01',
    region: '日本',
    datacenter: 'Equinix TY',
    cpu: 'AMD EPYC 7302',
    cpuCores: 32,
    memory: 256,
    disk: 4000,
    diskType: 'NVMe',
    virtualization: 'KVM',
    publicIp: '198.51.100.5',
    internalIp: '10.0.1.100',
    bandwidth: 1000,
    maxVms: 80,
    currentVms: 56,
    status: 'online',
    enabled: true,
    cpuUsage: 38,
    memoryUsage: 55,
    diskUsage: 42,
  },
  {
    id: '3',
    name: 'SG-Node-01',
    region: '新加坡',
    datacenter: 'DigitalOcean',
    cpu: 'Intel Xeon Gold 6248',
    cpuCores: 40,
    memory: 512,
    disk: 8000,
    diskType: 'NVMe',
    virtualization: 'KVM',
    publicIp: '192.0.2.10',
    internalIp: '10.0.2.100',
    bandwidth: 2000,
    maxVms: 100,
    currentVms: 78,
    status: 'maintenance',
    enabled: false,
    cpuUsage: 0,
    memoryUsage: 0,
    diskUsage: 35,
  },
  {
    id: '4',
    name: 'US-Node-01',
    region: '美国',
    datacenter: 'OVH',
    cpu: 'AMD EPYC 7402',
    cpuCores: 48,
    memory: 512,
    disk: 6000,
    diskType: 'SSD',
    virtualization: 'KVM',
    publicIp: '203.0.113.50',
    internalIp: '10.0.3.100',
    bandwidth: 1000,
    maxVms: 120,
    currentVms: 0,
    status: 'offline',
    enabled: false,
    cpuUsage: 0,
    memoryUsage: 0,
    diskUsage: 0,
  },
];
